### PR TITLE
Feat standardize output

### PR DESCRIPTION
**Pull request by morarucostel**
Closes #
Standardizing the output params of the Slack tasks, moving to Cloud event structure.

Sample of the output structure,
```
{"output":"{"id":"8a79762b-8548-4619-a043-b0cd4c549078","type":"SlackMembers","source":"boomerang-io/worker.flow/slack","specversion":"1.0","time":"2021-04-12T15:41:03.931Z","data":{"ok":true,"members":["U015BUU844T","U015NP9HNMP","U015NT49ZGR"],"response_metadata":{"next_cursor":"","scopes":["incoming-webhook","users:read.email","users:read","channels:read","groups:read","im:read","mpim:read","channels:manage","groups:write","im:write","mpim:write"],"acceptedScopes":["channels:read","groups:read","mpim:read","im:read","read"]}}}"}
```

#### Changelog

**New**

- NA

**Changed**

- All exposed APIs

**Removed**

- NA

### CODE REVIEW

**Comment by tlawrie** [comment]
Hey @morarucostel would we be better of adding the Cloud Events dependency to the utils and have a method that Is specifically for the event or is that not useful because it would be hard to generate the payload

My thinking is that they would just be able to send the subject and payload and the rest of it would be handled by the utils.

**Comment by morarucostel** [comment]
@tlawrie I agree with using the utils for a generic enough method. 
I've pushed a PR on the `worker.interfaces` to support this, https://github.com/boomerang-io/worker.interfaces/pull/2

Once that is approved, the library can use it with:
```
const { log, utils, ce } = require("@boomerang-io/worker-core");
process.cloudEventsContext = {
  source: "boomerang-io/worker.flow/slack"
};
....
ce.getCloudEvent("slack-conversations-invite", "ActionStatus", body)
```

**Comment by morarucostel** [comment]
@tlawrie I'll try to adapt the rest of the output messages to the new structure.

**Comment by morarucostel** [comment]
Closing the PR as irrelevant since we are running Tekton Tasks now.

**Pull request closed without merging**
